--- 
extensions: 
- extension-name-here
- second-extension-name
name: RubyConf
bbver: 4.6
sdk: /usr/local/lib/ruby/gems/1.8/gems/rhodes-1.4.0
applog: rholog.txt
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
version: 1.4.0
vendor: rhomobile
sdkversion: 1.4.0
iphone: 
  provisionprofile: 
  sdk: iphonesimulator3.0
  entitlements: 
  codesignidentity: 
  configuration: Debug
