--- 
extensions: 
- extension-name-here
- second-extension-name
name: RubyConf
bbver: 4.6
sdk: /Users/macboypro/src/rhodes  
applog: rholog.txt
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
version: 1.0
vendor: Blazing Cloud
sdkversion: 1.4.0
iphone: 
  provisionprofile: 
  sdk: iphonesimulator3.0
  entitlements: 
  codesignidentity: 
  configuration: Debug
