--- 
name: RubyConf
extensions: 
- extension-name-here
- second-extension-name
bbver: 4.6
sdk: c:/Ruby/lib/ruby/gems/1.8/gems/rhodes-1.4.0
version: 1.0
applog: rholog.txt
sdkversion: 1.4.0
vendor: Blazing Cloud
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
iphone: 
  configuration: Debug
  sdk: iphonesimulator3.0
  codesignidentity: 
  provisionprofile: 
  entitlements: 
